In [13]:
import pandas as pd
import numpy as np

In [63]:
df_orig = pd.read_parquet('/lustre/groups/ml01/workspace/ghaith.mqawass/2025_ghaith_de_novo_design/data/df_12props_canon_safe_encoding_filtered_ms.parquet')

In [66]:
keep_cols = ['SAFE', 'safe_tokens', 'seq_len', 'encoded','canon_smiles']
df_subset = df_orig[keep_cols]

In [67]:
df_subset

,SAFE,safe_tokens,seq_len,encoded,canon_smiles
0,C=C(c1ccc5cc1)C1COC2(CCCCC2)OO1.c16cccc(C(=C)C...,"[C, =, C, (, c, 1, c, c, c, 5, c, c, 1, ), C, ...",69,"[110, 107, 110, 93, 168, 98, 168, 168, 168, 10...",C=C(c1ccc(Oc2cccc(C(=C)C3COC4(CCCCC4)OO3)c2)cc...
1,c18ccsc15.c19nnc6s1.c17ccccc1.C3(=O)C4.NC8=O.N...,"[c, 1, 8, c, c, s, c, 1, 5, ., c, 1, 9, n, n, ...",56,"[168, 98, 105, 168, 168, 172, 168, 98, 102, 96...",NC(=O)c1ccsc1NC(=O)CSc1nnc(Nc2ccccc2)s1
2,c14cccc2c1c(O)c6c(=O)n2C.c15ccc7cc1.C7(C)(C)C....,"[c, 1, 4, c, c, c, c, 2, c, 1, c, (, O, ), c, ...",60,"[168, 98, 101, 168, 168, 168, 168, 99, 168, 98...",COc1cccc2c1c(O)c(C(=O)N(C)c1ccc(C(C)(C)C)cc1)c...
3,CN(C)C(=NO)c1ccc4cc1.c15cc6cc(F)c1.C16CCOCC1.S45,"[C, N, (, C, ), C, (, =, N, O, ), c, 1, c, c, ...",48,"[110, 114, 93, 110, 94, 110, 93, 107, 114, 115...",CN(C)C(=NO)c1ccc(Sc2cc(F)cc(C3CCOCC3)c2)cc1
4,CN=C(S)C16CCCCC15.S4(=O)(=O)c1ccc(F)cc1.c16ccc...,"[C, N, =, C, (, S, ), C, 1, 6, C, C, C, C, C, ...",58,"[110, 114, 107, 110, 93, 117, 94, 110, 98, 103...",CN=C(S)C1(c2cccnc2)CCCCC1CCNS(=O)(=O)c1ccc(F)cc1
...,...,...,...,...,...
1422432,c19nn2c(=O)c%10cnc2s1.N15CCN8CC1.c1%11ccccc1.C...,"[c, 1, 9, n, n, 2, c, (, =, O, ), c, %10, c, n...",65,"[168, 98, 106, 169, 169, 99, 168, 93, 107, 115...",CCCN(CCC)c1nn2c(=O)c(C(=O)N3CCN(Cc4ccccc4)CC3)...
1422433,c16c(N)n(C)c(=O)n(C)c1=O.S5(=O)(=O)c1ccccc1.C2...,"[c, 1, 6, c, (, N, ), n, (, C, ), c, (, =, O, ...",73,"[168, 98, 103, 168, 93, 114, 94, 169, 93, 110,...",CC(OC(=O)C(NS(=O)(=O)c1ccccc1)C(C)C)C(=O)c1c(N...
1422434,c15ncnc2cc(N)ncc12.c16ccc7cc1.CN6C.C47.N45,"[c, 1, 5, n, c, n, c, 2, c, c, (, N, ), n, c, ...",42,"[168, 98, 102, 169, 168, 169, 168, 99, 168, 16...",CN(C)c1ccc(CNc2ncnc3cc(N)ncc23)cc1
1422435,c19ccc(C)c2ccccc12.c18ccc(S5(=O)=O)cc1.c16cc9c...,"[c, 1, 9, c, c, c, (, C, ), c, 2, c, c, c, c, ...",68,"[168, 98, 106, 168, 168, 168, 93, 110, 94, 168...",CCC(C)c1ccc(S(=O)(=O)Nc2cc(-c3ccc(C)c4ccccc34)...


In [68]:
df1 = pd.read_parquet('/lustre/groups/ml01/workspace/ghaith.mqawass/2025_ghaith_de_novo_design/data/ms_data/fingerprints_from_pretrained_encoder/msg/msg_test_safe_encoded.parquet')

In [69]:
df2 = pd.read_parquet('/lustre/groups/ml01/workspace/ghaith.mqawass/2025_ghaith_de_novo_design/data/ms_data/fingerprints_from_pretrained_encoder/canopus/canopus_test_safe_encoded.parquet')

In [83]:
cd .. 

/ictstr01/home/icb/ghaith.mqawass/projs


In [ ]:
cd 

In [84]:
cd morflow2.0/DiffMS

/ictstr01/home/icb/ghaith.mqawass/projs/morflow2.0/DiffMS


In [3]:
fp_model

OrderedDict([('spectra_encoder.0.instrument_embedder',
              tensor([[1., 0., 0., 0., 0., 0.],
                      [0., 1., 0., 0., 0., 0.],
                      [0., 0., 1., 0., 0., 0.],
                      [0., 0., 0., 1., 0., 0.],
                      [0., 0., 0., 0., 1., 0.],
                      [0., 0., 0., 0., 0., 1.]], device='cuda:0')),
             ('spectra_encoder.0.form_embedder_mod._extra_embeddings',
              tensor([[ 5.9319e-40,  7.4357e-39,  3.3764e-38,  4.2064e-38,  1.6358e-38,
                        3.4094e-38,  3.4617e-38,  7.3819e-39, -2.8635e-38]], device='cuda:0')),
             ('spectra_encoder.0.form_embedder_mod.int_to_feat_matrix',
              tensor([[0.0000e+00, 0.0000e+00, 0.0000e+00,  ..., 0.0000e+00, 0.0000e+00,
                       0.0000e+00],
                      [2.0000e+00, 1.0000e+00, 2.9289e-01,  ..., 1.2046e-03, 3.0118e-04,
                       7.5281e-05],
                      [0.0000e+00, 2.0000e+00, 1.0000e+00,  

In [113]:
from src.mist.models.spectra_encoder import SpectraEncoderGrowing
import torch
checkpoint_diff = '/home/icb/ghaith.mqawass/projs/morflow2.0/pretrained_mist/checkpoints/encoder_msg.pt'
fp_model = torch.load(checkpoint_diff, map_location=torch.device("cuda"))
# encoder_hidden_dim= 256           # Small Model Default (CANOPUS)
encoder_hidden_dim= 512          # Large Model Default (MSG)
# encoder_magma_modulo= 512         # Small Model Default (CANOPUS)
encoder_magma_modulo= 2048       # Large Model Default (MSG)
encoder = SpectraEncoderGrowing(
            inten_transform='float',
            inten_prob=0.1,
            remove_prob=0.5,
            peak_attn_layers=2,
            num_heads=8,
            pairwise_featurization=True,
            embed_instrument=False,
            cls_type='ms1',
            set_pooling='cls',
            spec_features='peakformula',
            mol_features='fingerprint',
            form_embedder='pos-cos',
            output_size=4096,
            hidden_size=encoder_hidden_dim,
            spectra_dropout=0.1,
            top_layers=1,
            refine_layers=4,
            magma_modulo=encoder_magma_modulo,
        )

In [114]:
encoder.load_state_dict(fp_model)

<All keys matched successfully>

In [97]:
encoder.spectra_encoder[0]

FormulaTransformer(
  (form_embedder_mod): FourierFeaturizerPosCos()
  (intermediate_layer): MLPBlocks(
    (activation): ReLU()
    (dropout_layer): Dropout(p=0.1, inplace=False)
    (input_layer): Linear(in_features=343, out_features=512, bias=True)
    (layers): ModuleList(
      (0): Linear(in_features=512, out_features=512, bias=True)
    )
  )
  (pairwise_featurizer): MLPBlocks(
    (activation): ReLU()
    (dropout_layer): Dropout(p=0.1, inplace=False)
    (input_layer): Linear(in_features=162, out_features=512, bias=True)
    (layers): ModuleList(
      (0): Linear(in_features=512, out_features=512, bias=True)
    )
  )
  (peak_attn_layers): ModuleList(
    (0-1): 2 x TransformerEncoderLayer(
      (self_attn): MultiheadAttention(
        (out_proj): NonDynamicallyQuantizableLinear(in_features=512, out_features=512, bias=True)
      )
      (linear1): Linear(in_features=512, out_features=2048, bias=True)
      (dropout): Dropout(p=0.1, inplace=False)
      (linear2): Linear(in_

In [87]:
encoder.eval()

SpectraEncoderGrowing(
  (spectra_encoder): ModuleList(
    (0): FormulaTransformer(
      (form_embedder_mod): FourierFeaturizerPosCos()
      (intermediate_layer): MLPBlocks(
        (activation): ReLU()
        (dropout_layer): Dropout(p=0.1, inplace=False)
        (input_layer): Linear(in_features=343, out_features=256, bias=True)
        (layers): ModuleList(
          (0): Linear(in_features=256, out_features=256, bias=True)
        )
      )
      (pairwise_featurizer): MLPBlocks(
        (activation): ReLU()
        (dropout_layer): Dropout(p=0.1, inplace=False)
        (input_layer): Linear(in_features=162, out_features=256, bias=True)
        (layers): ModuleList(
          (0): Linear(in_features=256, out_features=256, bias=True)
        )
      )
      (peak_attn_layers): ModuleList(
        (0-1): 2 x TransformerEncoderLayer(
          (self_attn): MultiheadAttention(
            (out_proj): NonDynamicallyQuantizableLinear(in_features=256, out_features=256, bias=True)
    

In [1]:
data_path = '/lustre/groups/ml01/workspace/ghaith.mqawass/2025_ghaith_de_novo_design/data/ms_data'

In [2]:
from types import SimpleNamespace

def dict_to_namespace(d):
    if isinstance(d, dict):
        return SimpleNamespace(**{k: dict_to_namespace(v) for k, v in d.items()})
    return d

cfg = {"dataset": {
    "name": "msg",
    "remove_h": None,
    "stats_dir": None,
    "datadir": data_path + "/msg",
    "filter": False,
    "denoise_nodes": False,
    "merge": "downproject_4096",
    "morgan_nbits": 2048,
    "morgan_r": 2,
    "split_file": data_path + "/msg/split.tsv",
    "spec_features": "peakformula",
    "mol_features": "fingerprint",
    "subform_folder": data_path + "/msg/subformulae/default_subformulae",
    "augment_data": False,
    "remove_prob": 0.1,
    "remove_weights": "exp",
    "inten_prob": 0.1,
    "inten_transform": "float",
    "cls_type": "ms1",
    "magma_aux_loss": False,
    "labels_file": data_path + "/msg/labels.tsv",
    "spec_folder": data_path + "/msg/spec_files",
    "cache_featurizers": True,
    "set_pooling": "cls",
    "max_count": None,
}}

# Convert to namespace
cfg = dict_to_namespace(cfg)

print(cfg.dataset.datadir)

/lustre/groups/ml01/workspace/ghaith.mqawass/2025_ghaith_de_novo_design/data/ms_data/msg


In [3]:
cd projs/morflow2.0/DiffMS/

/ictstr01/home/icb/ghaith.mqawass/projs/morflow2.0/DiffMS


In [4]:
# import sys, os
# sys.path.append("/ictstr01/home/icb/ghaith.mqawass/projs/morflow2.0/DiffMS")

In [ ]:
import pandas as pd

In [5]:
from src.datasets import spec2mol_dataset
datamodule = spec2mol_dataset.Spec2MolDataModule(cfg=cfg) 

/lustre/groups/ml01/workspace/ghaith.mqawass/flow/lib/python3.10/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


: 

: 


KeyboardInterrupt



In [102]:
len(datamodule.test_dataset)

17082

In [103]:
len(datamodule.val_dataset)

19043

In [114]:
from tqdm import tqdm
results = []
for batch in tqdm(datamodule.val_dataloader()):
    output,aux = encoder(batch)
    results.append(output)

100%|██████████| 19043/19043 [11:34<00:00, 27.41it/s]


In [106]:
import numpy as np

In [115]:
fps = np.array([(t>= 0.5).float().squeeze(0) for t in results])

In [116]:
fps.shape

(19043, 4096)

In [117]:
smiles = [datamodule.val_dataset[i]['mol'][0]['smiles'] for i in range(len(datamodule.val_dataset))]
inchis = [datamodule.val_dataset[i]['mol'][0]['inchikey'] for i in range(len(datamodule.val_dataset))]

In [119]:
import pandas as pd
fps_list = [row.tolist() for row in fps]

# Create DataFrame
df = pd.DataFrame({
    "smiles": smiles,
    "inchi": inchis,
    "fingerprint": fps_list
})

In [121]:
df.to_parquet('/lustre/groups/ml01/workspace/ghaith.mqawass/2025_ghaith_de_novo_design/data/ms_data/fingerprints_from_pretrained_encoder/msg/msg_val.parquet')

In [47]:
fps_list = df["fingerprint"].tolist()  
fps_array = np.array(fps_list, dtype=np.float32)